// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMTCUZoU-AnWnVvaG_vNGvKIvipGQBmnU',
    appId: '1:771195922447:web:aebf873856a05f4f1a9b7a',
    messagingSenderId: '771195922447',
    projectId: 'micro-teaching-studio',
    authDomain: 'micro-teaching-studio.firebaseapp.com',
    storageBucket: 'micro-teaching-studio.firebasestorage.app',
    measurementId: 'G-P3D04M6CBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbWLxMqtcAY74Ozi_2w_cpTtwFD0zC4TY',
    appId: '1:771195922447:android:25db46836ff34f781a9b7a',
    messagingSenderId: '771195922447',
    projectId: 'micro-teaching-studio',
    storageBucket: 'micro-teaching-studio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPQ_7n0j68CzI5XoXyAzWuR7PcyxGP5F4',
    appId: '1:771195922447:ios:7f4adc6b482cd4701a9b7a',
    messagingSenderId: '771195922447',
    projectId: 'micro-teaching-studio',
    storageBucket: 'micro-teaching-studio.firebasestorage.app',
    iosBundleId: 'ayman.micro.teaching.studio',
  );
}
