/// Flutter icons WhatsApp
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WhatsApp
///      fonts:
///       - asset: fonts/WhatsApp.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const IconData whatsapp =
      IconData(0xf232, fontFamily: 'WhatsApp', fontPackage: null);
  static const IconData contactCall =
      IconData(0xe801, fontFamily: 'contact_call', fontPackage: null);
  static const IconData mail =
      IconData(0xe802, fontFamily: 'mail', fontPackage: null);
  static const IconData instagram =
      IconData(0xf16d, fontFamily: 'instagram', fontPackage: null);
  static const IconData phoneLandline =
      IconData(0xe803, fontFamily: 'phone_landline', fontPackage: null);
}
